# Generated by Django 4.2.26 on 2025-11-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_userapikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên gói')),
                ('days', models.PositiveIntegerField(verbose_name='Số ngày')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gói gia hạn',
                'verbose_name_plural': 'Gói gia hạn',
                'ordering': ['days'],
            },
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=200, verbose_name='Tên tài khoản')),
                ('account_number', models.CharField(max_length=50, verbose_name='Số tài khoản')),
                ('bank_code', models.CharField(max_length=20, verbose_name='Mã ngân hàng')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='Tên ngân hàng')),
                ('transfer_content', models.CharField(max_length=500, verbose_name='Nội dung chuyển khoản')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Thông tin chuyển khoản',
                'verbose_name_plural': 'Thông tin chuyển khoản',
                'ordering': ['-created_at'],
            },
        ),
    ]
