# Generated by Django 4.2.26 on 2025-11-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0003_extensionpackage_paymentinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionpackage',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Số tiền (VNĐ)'),
        ),
    ]
