# Generated by Django 4.2.26 on 2025-11-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0004_extensionpackage_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinfo',
            name='transfer_content',
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='note',
            field=models.CharField(blank=True, help_text='Ghi chú không bắt buộc, có thể để trống', max_length=500, null=True, verbose_name='Ghi chú'),
        ),
    ]
