# Generated by Django 4.2.26 on 2025-11-12 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0005_remove_paymentinfo_transfer_content_paymentinfo_note'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='license',
            table='license_zalo',
        ),
    ]
