# Generated by Django 4.2.26 on 2025-11-12 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('licenses', '0006_rename_license_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseTikTok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên license')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiktok_licenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'License TikTok',
                'verbose_name_plural': 'Licenses TikTok',
                'db_table': 'license_tiktok',
                'ordering': ['-created_at'],
            },
        ),
    ]
