# Generated by Django 4.2.26 on 2025-11-12 01:50

from django.db import migrations, models
import django.utils.timezone


def set_default_expired_at(apps, schema_editor):
    LicenseTikTok = apps.get_model('licenses', 'LicenseTikTok')
    # Set expired_at = created_at + 30 days for existing records
    for license in LicenseTikTok.objects.all():
        if not license.expired_at:
            from datetime import timedelta
            license.expired_at = license.created_at + timedelta(days=30)
            license.save(update_fields=['expired_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0007_licensetiktok'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensetiktok',
            name='expired_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hết hạn'),
        ),
        migrations.RunPython(set_default_expired_at, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='licensetiktok',
            name='expired_at',
            field=models.DateTimeField(verbose_name='Hết hạn'),
        ),
    ]
