# Generated by Django 4.2.26 on 2025-11-30 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0010_replace_name_with_shop_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionPackageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên nhóm')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã nhóm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nhóm gói gia hạn',
                'verbose_name_plural': 'Nhóm gói gia hạn',
            },
        ),
        migrations.AddField(
            model_name='extensionpackage',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='licenses.extensionpackagegroup', verbose_name='Nhóm gói'),
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_infos', to='licenses.extensionpackagegroup', verbose_name='Nhóm gói'),
        ),
    ]
