# Generated by Django 4.2.26 on 2025-11-30 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0011_extensionpackagegroup_extensionpackage_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinfo',
            name='group',
        ),
    ]
